package utils;

public enum UIText {

    ADMIN_LOGS_ALL("admin.logs_all"),
    ADMIN_LOGS_BY_USER("admin.logs_by_user"),
    ADMIN_LOGS_SESSION("admin.logs_session"),
    ADMIN_LOGS_RECENT("admin.logs_recent"),
    ADMIN_EMPTY_LOGS("admin.empty_logs"),
    ADMIN_NO_ACTIVE_USER("admin.no_active_user"),
    ADMIN_MENU_TITLE("admin.menu_title"),
    ADMIN_GET_ALL_USERS("admin.get_all_users"),
    ADMIN_CREATE_USER("admin.create_user"),
    ADMIN_DELETE_USER("admin.delete_user"),
    ADMIN_BAN_USER("admin.ban_user"),
    ADMIN_UNBAN_USER("admin.unban_user"),
    ADMIN_NO_USERS("admin.no_users"),
    ADMIN_USER_BANNED("admin.user_banned"),
    ADMIN_USER_UNBANNED("admin.user_unbanned"),
    ADMIN_USER_DELETED("admin.user_deleted"),
    ADMIN_HEADER_USER("admin.header_user"),
    ADMIN_NO_LOGS("admin.no_logs"),
    ADMIN_RECENT_LOGS_PREFIX("admin.recent_logs_prefix"),

    MENU_TITLE_UNIVERSITY("menu.title_university"),
    MENU_TITLE_AUTH("menu.title_auth"),
    MENU_MY_PROFILE("menu.my_profile"),
    MENU_RESEARCH("menu.research"),
    MENU_NEWS("menu.news"),
    MENU_COURSES("menu.courses"),
    MENU_MESSENGER("menu.messenger"),
    MENU_TECH_REQUEST("menu.tech_request"),
    MENU_STUDENT("menu.student"),
    MENU_ADMIN("menu.admin"),
    MENU_TECH_SPECIALIST("menu.tech_specialist"),
    MENU_MANAGER("menu.manager"),
    MENU_TEACHER("menu.teacher"),
    MENU_NOTIFICATIONS("menu.notifications"),
    MENU_BACK("menu.back"),
    MENU_AUTH_LOGIN("menu.auth_login"),
    MENU_AUTH_EXIT("menu.auth_exit"),
    MENU_COMPLAINT("menu.complaint"),

    MENU_CHOOSE("menu.choose"),
    MENU_EXIT("menu.exit"),

    AUTH_CHANGE_LANG("auth.change_lang"),
    AUTH_SIGN_UP("auth.sign_up"),
    AUTH_LOG_IN("auth.log_in"),
    AUTH_GOODBYE("auth.goodbye"),
    AUTH_WELCOME("auth.welcome"),

    INPUT_LOGIN("input.login"),
    INPUT_PASSWORD("input.password"),
    INPUT_ROLE("input.role"),
    INPUT_USER_ROLE("input.user_role"),
    INPUT_NAME("input.name"),
    INPUT_SURNAME("input.surname"),
    INPUT_TARGET_LOGIN("input.target_login"),
    INPUT_NEW_NAME("input.new_name"),
    INPUT_NEW_SURNAME("input.new_surname"),
    INPUT_NEW_PASSWORD("input.new_password"),
    INPUT_BAN("input.ban"),
    INPUT_COURSE_NAME("input.course_name"),
    INPUT_COURSE_DESC("input.course_desc"),
    INPUT_COURSE_CREDITS("input.course_credits"),
    INPUT_COURSE_TYPE("input.course_type"),
    INPUT_TEACHER_TYPE("input.teacher_type"),
    INPUT_COURSE_TEACHER_TYPE("input.course_teacher_type"),
    INPUT_EMPLOYEE_ID("input.employee_id"),
    INPUT_STUDENT_ID("input.student_id"),
    INPUT_SUPERVISOR_ID("input.supervisor_id"),
    INPUT_USER_ID("input.user_id"),
    INPUT_LECTURER_ID("input.lecturer_id"),
    INPUT_TEACHER_ID("input.teacher_id"),
    INPUT_PRACTICE_ID("input.practice_id"),
    INPUT_ENROLLMENT_ID("input.enrollment_id"),
    INPUT_POINTS_TO_ADD("input.points_to_add"),
    INPUT_COURSE_ID("input.course_id"),
    INPUT_PROJECT_ID("input.project_id"),
    INPUT_PAPER_ID("input.paper_id"),
    INPUT_PAPER_TITLE("input.paper_title"),
    INPUT_PROJECT_TOPIC("input.project_topic"),
    INPUT_RESEARCH_PROFILE_USER_ID("input.research_profile_user_id"),
    INPUT_RESEARCHER_USER_ID("input.researcher_user_id"),
    INPUT_ORG_ID("input.org_id"),
    INPUT_ORG_NAME("input.org_name"),
    INPUT_ORG_DESC("input.org_desc"),
    INPUT_SENDER_ID("input.sender_id"),
    INPUT_RECEIVER_ID("input.receiver_id"),
    INPUT_MESSAGE_ID("input.message_id"),
    INPUT_NEWS_ID("input.news_id"),
    INPUT_CHAT_ID("input.chat_id"),
    INPUT_REQUEST_ID("input.request_id"),
    INPUT_MESSAGE_CONTENT("input.message_content"),
    INPUT_COMMENT("input.comment"),
    INPUT_NEWS_TITLE("input.news_title"),

    INPUT_COMPLAINT_LEVEL("input.complaint_level"),
    INPUT_TECH_REQ_STATUS("input.tech_req_status"),

    USER_UPDATE("user.update"),
    USER_DELETE("user.delete"),
    USER_CREATE_ADMIN("user.create_admin"),
    USER_CREATE_STUDENT("user.create_student"),
    USER_CREATE_TEACHER("user.create_teacher"),
    USER_CREATE_MANAGER("user.create_manager"),
    USER_CREATE_SUPPORT("user.create_support"),
    COURSE_CREATE("course.create"),
    ORG_CREATE("org.create"),
    ORG_GET_BY_ID("org.get_by_id"),
    ORG_DELETE("org.delete"),
    ORG_ADD_MEMBER("org.add_member"),
    ORG_REMOVE_MEMBER("org.remove_member"),
    ORG_SET_PRESIDENT("org.set_president"),
    ORG_REMOVE_PRESIDENT("org.remove_president"),
    ENROLL_CREATE("enroll.create"),
    ENROLL_DROP("enroll.drop"),
    MENU_VIEW_ALL("menu.view_all"),
    ENROLL_VIEW_STUDENT("enroll.view_student"),
    MSG_SEND("msg.send"),
    MSG_INBOX("msg.inbox"),
    MSG_DELETE("msg.delete"),

    MSG_INVALID_CHOICE("msg.invalid_choice"),
    MSG_INPUT_EMPTY("msg.input_empty"),
    MSG_INPUT_NUMBER("msg.input_number"),
    MSG_INPUT_RANGE("msg.input_range"),
    MSG_INPUT_YES_NO("msg.input_yes_no"),
    MSG_REGISTERED("msg.registered"),
    MSG_CREATED("msg.created"),
    MSG_DELETED("msg.deleted"),
    MSG_SENT("msg.sent"),
    MSG_ALL_ORGANIZATIONS("msg.all_organizations"),
    MSG_MEMBERS_IDS("msg.members_ids"),
    MSG_STUDENTS_HEADER("msg.students_header"),
    MSG_NO_USERS("msg.no_users"),
    MSG_NO_COURSES("msg.no_courses"),
    MSG_NO_TEACHERS("msg.no_teachers"),
    NO_COURSE_TEACHERS("msg.no_course_teachers"),
    MSG_NO_NEWS("msg.no_news"),
    MSG_NO_ORGANIZATIONS("msg.no_organizations"),
    MSG_NO_RESEARCHERS("msg.no_researchers"),
    MSG_NO_PAPERS("msg.no_papers"),
    MSG_NO_ENROLLMENTS("msg.no_enrollments"),
    MSG_NO_COMPLAINTS("msg.no_complaints"),
    MSG_NO_PENDING_COMPLAINTS("msg.no_pending_complaints"),
    MSG_NO_REQUESTS("msg.no_requests"),
    MSG_NO_TECH_REQUESTS("msg.no_tech_requests"),
    MSG_NO_EMPLOYEES("msg.no_employees"),
    MSG_NO_TECH_SPECIALISTS("msg.no_tech_specialists"),
    MSG_NO_STUDENTS("msg.no_students"),
    MSG_NO_GRADUATE_STUDENTS("msg.no_graduate_students"),
    MSG_NO_DEANS("msg.no_deans"),
    MSG_NO_NOTIFICATIONS("msg.no_notifications"),
    MSG_BECAME_RESEARCHER("msg.became_researcher"),
    MSG_PAPER_CITED("msg.paper_cited"),
    MSG_PAPER_CREATED("msg.paper_created"),
    MSG_PAPER_DELETED("msg.paper_deleted"),
    MSG_PARTICIPANT_ADDED("msg.participant_added"),
    MSG_PARTICIPANT_REMOVED("msg.participant_removed"),
    MSG_REFERENCE_ADDED("msg.reference_added"),
    MSG_NO_MY_PAPERS("msg.no_my_papers"),
    MSG_NO_RESEARCHERS_AVAILABLE("msg.no_researchers_available"),
    MSG_NO_PARTICIPANTS_TO_REMOVE("msg.no_participants_to_remove"),
    MSG_NO_PAPERS_TO_REFERENCE("msg.no_papers_to_reference"),
    MSG_RESEARCHER_NO_PAPERS("msg.researcher_no_papers"),
    MSG_COURSE_CREATED("msg.course_created"),
    MSG_COURSE_DELETED("msg.course_deleted"),
    MSG_TEACHER_ASSIGNED("msg.teacher_assigned"),
    MSG_NEWS_POSTED("msg.news_posted"),
    MSG_NEWS_DELETED("msg.news_deleted"),
    MSG_MARK_RECORDED("msg.mark_recorded"),
    MSG_COMPLAINT_SENT("msg.complaint_sent"),
    MSG_COMPLAINT_CLOSED("msg.complaint_closed"),
    MSG_REQUEST_UPDATED("msg.request_updated"),
    MSG_TECH_REQUEST_SENT("msg.tech_request_sent"),
    MSG_JOINED_ORG("msg.joined_org"),
    MSG_ORG_CREATED("msg.org_created"),
    MSG_MEMBER_ADDED("msg.member_added"),
    MSG_MEMBER_REMOVED("msg.member_removed"),
    MSG_ORG_DELETED("msg.org_deleted"),
    MSG_LEFT_ORG("msg.left_org"),
    MSG_ENROLLED_IN("msg.enrolled_in"),
    MSG_NOT_ENROLLED("msg.not_enrolled"),
    MSG_NO_MEMBERS_TO_REMOVE("msg.no_members_to_remove"),
    MSG_NO_STUDENTS_TO_ADD("msg.no_students_to_add"),
    MSG_CHOOSE_COURSE("msg.choose_course"),
    MSG_CHOOSE_LECTURE_TEACHER("msg.choose_lecture_teacher"),
    MSG_CHOOSE_PRACTICE_TEACHER("msg.choose_practice_teacher"),
    MSG_GPA_OVERALL("msg.gpa_overall"),
    MSG_NO_ENROLLMENTS_SHORT("msg.no_enrollments_short"),
    MSG_AVG_GPA("msg.avg_gpa"),
    MSG_OVERALL_AVG_GPA("msg.overall_avg_gpa"),
    MSG_REQUESTS_BY_STATUS("msg.requests_by_status"),
    MSG_NO_REQUESTS_STATUS("msg.no_requests_status"),
    MSG_NOTIFICATION_UNREAD_PREFIX("msg.notification_unread_prefix"),
    MSG_MEMBER_ADDED_TO("msg.member_added_to"),
    MSG_MEMBER_REMOVED_FROM("msg.member_removed_from"),
    MSG_GPA_LINE("msg.gpa_line"),
    MSG_NO_ENROLLMENTS_LINE("msg.no_enrollments_line"),
    MSG_NO_TECH_SPECIALISTS_AVAILABLE("msg.no_tech_specialists_available"),
    MSG_NO_TECH_REQUESTS_YET("msg.no_tech_requests_yet"),
    MSG_NO_COMPLAINTS_YET("msg.no_complaints_yet"),

    RESEARCH_MENU_TITLE("research.menu_title"),
    RESEARCH_PAPERS_MENU_TITLE("research.papers_menu_title"),
    RESEARCH_HEADER_RESEARCHERS("research.header_researchers"),
    RESEARCH_HEADER_RESEARCHER_PAPERS("research.header_researcher_papers"),
    RESEARCH_VIEW_RESEARCHERS("research.view_researchers"),
    RESEARCH_PAPER_MENU("research.paper_menu"),
    RESEARCH_BECOME("research.become"),
    RESEARCH_MANAGE_PAPERS("research.manage_papers"),
    RESEARCH_MENU_RESEARCHERS("research.menu_researchers"),
    RESEARCH_PAPERS_BY_DATE("research.papers_by_date"),
    RESEARCH_PAPERS_BY_CITATIONS("research.papers_by_citations"),
    RESEARCH_PAPERS_BY_VIEWS("research.papers_by_views"),
    RESEARCH_VIEW_PAPER("research.view_paper"),
    RESEARCH_CITE_PAPER("research.cite_paper"),
    RESEARCH_MANAGE_TITLE("research.manage_title"),
    RESEARCH_VIEW_MY_PAPERS("research.view_my_papers"),
    RESEARCH_CREATE_PAPER("research.create_paper"),
    RESEARCH_DELETE_PAPER("research.delete_paper"),
    RESEARCH_ADD_PARTICIPANT("research.add_participant"),
    RESEARCH_REMOVE_PARTICIPANT("research.remove_participant"),
    RESEARCH_ADD_REFERENCE("research.add_reference"),
    RESEARCH_HEADER_PARTICIPANTS("research.header_participants"),
    RESEARCH_HEADER_MY_PAPERS("research.header_my_papers"),
    RESEARCH_HEADER_AVAILABLE_PAPERS("research.header_available_papers"),
    RESEARCH_HEADER_PAPERS("research.header_papers"),

    NEWS_MENU_TITLE("news.menu_title"),
    NEWS_NO_NEWS("news.no_news"),
    NEWS_LEAVE_COMMENT("news.leave_comment"),

    COURSE_MENU_TITLE("course.menu_title"),
    COURSE_ENROLL("course.enroll"),
    COURSE_HEADER_COURSES("course.header_courses"),

    STUDENT_MENU_TITLE("student.menu_title"),
    STUDENT_TRANSCRIPT("student.transcript"),
    STUDENT_ORG_MENU("student.org_menu"),
    STUDENT_ORG_VIEW_ALL("student.org_view_all"),
    STUDENT_ORG_VIEW_DETAIL("student.org_view_detail"),
    STUDENT_ORG_VIEW_MINE("student.org_view_mine"),
    STUDENT_ORG_JOIN("student.org_join"),
    STUDENT_ORG_CREATE("student.org_create"),
    STUDENT_ORG_ADD_MEMBER("student.org_add_member"),
    STUDENT_ORG_REMOVE_MEMBER("student.org_remove_member"),
    STUDENT_ORG_DELETE("student.org_delete"),
    STUDENT_ORG_LEAVE("student.org_leave"),
    STUDENT_HEADER_ORGANIZATIONS("student.header_organizations"),
    STUDENT_HEADER_MEMBERS("student.header_members"),
    GRADUATE_CHECK_SUPERVISOR("graduate.check_supervisor"),
    GRADUATE_REJECT_SUPERVISOR("graduate.reject_supervisor"),
    GRADUATE_SUPERVISOR_REJECTED("graduate.supervisor_rejected"),

    TEACHER_MENU_TITLE("teacher.menu_title"),
    TEACHER_VIEW_COURSES("teacher.view_courses"),
    TEACHER_VIEW_STUDENTS("teacher.view_students"),
    TEACHER_PUT_MARK("teacher.put_mark"),
    TEACHER_COMPLAINT_MENU("teacher.complaint_menu"),
    TEACHER_VIEW_COMPLAINTS("teacher.view_complaints"),
    TEACHER_SEND_COMPLAINT("teacher.send_complaint"),
    TEACHER_HEADER_STUDENTS("teacher.header_students"),
    TEACHER_HEADER_DEANS("teacher.header_deans"),
    TEACHER_HEADER_COURSES("teacher.header_courses"),
    TEACHER_ENROLLMENTS_SUFFIX("teacher.enrollments_suffix"),
    TEACHER_BECOME_SUPERVISOR("teacher.become_supervisor"),
    TEACHER_SUCCESS_SUPERVISOR("teacher.success_supervisor"),

    DEAN_MENU_TITLE("dean.menu_title"),
    DEAN_VIEW_COMPLAINTS("dean.view_complaints"),
    DEAN_CLOSE_COMPLAINT("dean.close_complaint"),
    DEAN_HEADER_COMPLAINTS("dean.header_complaints"),

    MANAGER_MENU_TITLE("manager.menu_title"),
    MANAGER_VIEW_COURSES("manager.view_courses"),
    MANAGER_CREATE_COURSE("manager.create_course"),
    MANAGER_DELETE_COURSE("manager.delete_course"),
    MANAGER_ASSIGN_TEACHER("manager.assign_teacher"),
    MANAGER_VIEW_NEWS("manager.view_news"),
    MANAGER_CREATE_NEWS("manager.create_news"),
    MANAGER_DELETE_NEWS("manager.delete_news"),
    MANAGER_GPA_BY_STUDENT("manager.gpa_by_student"),
    MANAGER_GPA_BY_COURSE("manager.gpa_by_course"),
    MANAGER_GPA_BY_TEACHER("manager.gpa_by_teacher"),
    MANAGER_HEADER_NEWS("manager.header_news"),
    MANAGER_HEADER_GPA_STUDENT("manager.header_gpa_student"),
    MANAGER_HEADER_GPA_COURSE("manager.header_gpa_course"),
    MANAGER_HEADER_GPA_TEACHER("manager.header_gpa_teacher"),
    MANAGER_HEADER_TEACHERS("manager.header_teachers"),

    EMPLOYEE_MESSENGER_TITLE("employee.messenger_title"),
    EMPLOYEE_START_CHAT("employee.start_chat"),
    EMPLOYEE_TECH_MENU_TITLE("employee.tech_menu_title"),
    EMPLOYEE_VIEW_REQUESTS("employee.view_requests"),
    EMPLOYEE_SEND_REQUEST("employee.send_request"),
    EMPLOYEE_SEND_MESSAGE("employee.send_message"),
    EMPLOYEE_HEADER_EMPLOYEES("employee.header_employees"),
    EMPLOYEE_HEADER_TECH_SPECIALISTS("employee.header_tech_specialists"),

    TECH_MENU_TITLE("tech.menu_title"),
    TECH_VIEW_ALL_REQUESTS("tech.view_all_requests"),
    TECH_VIEW_BY_STATUS("tech.view_by_status"),
    TECH_UPDATE_REQUEST("tech.update_request"),
    TECH_HEADER_MY_REQUESTS("tech.header_my_requests"),

    NOTIFICATION_MENU_TITLE("notification.menu_title"),
    NOTIFICATION_MARK_ALL_READ("notification.mark_all_read"),
    NOTIFY_RESEARCHER_PROFILE("notification.researcher_profile"),
    NOTIFY_PAPER_PARTICIPANT("notification.paper_participant"),
    NOTIFY_ORG_PRESIDENT("notification.org_president"),
    NOTIFY_ORG_NEW_PRESIDENT("notification.org_new_president"),
    NOTIFY_TECH_REQUEST_NEW("notification.tech_request_new"),
    NOTIFY_TECH_REQUEST_DONE("notification.tech_request_done"),

    TECH_HEADER_STATUS_REQUESTS("tech.header_status_requests"),

    SUCCESS("msg.success"),
    FAIL("msg.fail"),

    ERR_LIST_IS_EMPTY("err.list_is_empty"),
    ERR_INVALID_CREDENTIALS("err.invalid_credentials"),
    ERR_USER_BANNED_OR_DELETED("err.user_banned_or_deleted"),
    ERR_USER_LOGIN("err.user_login"),
    ERR_DELETE_SYSTEM_USER("err.delete_system_user"),
    ERR_BAN_SYSTEM_USER("err.ban_system_user"),
    ERR_BAN_SELF("err.ban_self"),
    ERR_IMMUTABLE_ID("err.immutable_id"),
    ERR_FIELD_EMPTY("err.field_empty"),
    ERR_FIELD_PASSWORD_WEAK("err.field_password_weak"),
    ERR_FIELD_SINGLE_WORD("err.field_single_word"),
    ERR_FIELD_POSITIVE("err.field_positive"),
    ERR_FIELD_OUT_OF_RANGE("err.field_out_of_range"),
    ERR_FIELD_NULL("err.field_null"),
    GRADUATE_HAS_SUPERVISOR("err.graduate_has_supervisor"),
    GRADUATE_NO_SUPERVISOR("err.graduate_no_supervisor");

    private final String key;

    UIText(String key) {
        this.key = key;
    }

    public String localized(Object... args){
        return Translator.translate(key, args);
    }

    public String getKey() {
        return key;
    }
}
